services:
  backend:
    container_name: soimfalante-backend
    ports:
      - "8080:8080"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

  database:
    image: postgres:18
    container_name: soimfalante-database
    restart: always
    ports:
      - "5433:5432"
    env_file: ./backend/src/environments/.env
    volumes:
      - ./postgresql:/var/lib/postgresql
  
  minio:
    container_name: soimfalante-minio
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ./backend/src/environments/.env
    command: >
      server /data
      --address ":9000"
      --console-address ":9001"
    volumes:
      - ./minio:/data

